[package]
name = "hpm6750evkmini"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hpm-ral = { path = "../../", features = ["hpm6750"] }
