MEMORY
{
  CORE0_ILM_SLV : ORIGIN = 0x01000000, LENGTH = 256K
  CPU0_DLM_SLV : ORIGIN = 0x01040000, LENGTH = 256K
  AXI_SRAM : ORIGIN = 0x01080000, LENGTH = 1M
}

REGION_ALIAS("REGION_TEXT", CORE0_ILM_SLV);
REGION_ALIAS("REGION_RODATA", CPU0_DLM_SLV);
REGION_ALIAS("REGION_DATA", CPU0_DLM_SLV);
REGION_ALIAS("REGION_BSS", AXI_SRAM);
REGION_ALIAS("REGION_HEAP", AXI_SRAM);
REGION_ALIAS("REGION_STACK", AXI_SRAM);
