on:
  push:
    branches: [ main ]
  pull_request:

name: Continuous integration

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      matrix:
        # All generated code should be running on stable now, MSRV is 1.62.0
        rust: [1.62.0, stable, nightly]
        include:
          - rust: nightly
            experimental: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: riscv32imac-unknown-none-elf
          components: rustfmt
          override: true
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install svdtools for patch svds
        run: pip install svdtools
      - name: Run make and check under ${{ matrix.rust }}
        run: make TARGET=riscv32imac-unknown-none-elf
      - name: Check if the commit is latest
        run: bash script/check_latest.sh
      - name: Collect cache for rustup and Cargo
        if: always()
        uses: actions/cache@v3
        with:
          path: |
            ~/.rustup/
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ env.RUSTC_HASH }}-${{ hashFiles('**/Cargo.lock') }}
